services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sgr_backend
    restart: always
    ports:
      - "3008:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sgr_net

  db:
    image: mysql:8.0
    container_name: sgr_mysql
    restart: always
    command: >
      --default-authentication-plugin=mysql_native_password
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT_HOST:-3308}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sgr_net

volumes:
  mysql_data:

networks:
  sgr_net:
    driver: bridge